services:
  chugmania:
    container_name: chugmania
    build:
      dockerfile: dockerfile
      args:
        DB_FILE_NAME: local.db
        PRIVATE_KEY: somekey
        ISSUER: kallerud.no
        TOKEN_EXPIRY: 7d
        NODE_ENV: development
        ORIGIN: http://10.0.0.136:3000
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
    environment:
      NODE_ENV: development
      ORIGIN: http://10.0.0.136:3000
    restart: always
