name: Build and Push Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            DB_FILE_NAME=${{ vars.DB_FILE_NAME }}
            PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
            ISSUER=${{ secrets.ISSUER }}
            TOKEN_EXPIRY=${{ secrets.TOKEN_EXPIRY }}
            NODE_ENV: development
          tags: ${{ vars.DOCKER_USERNAME }}/chugmania
